CREATE TABLE TIM
(
	ID NUMBER,
	NAZIV VARCHAR(70) UNIQUE NOT NULL,
	MAKS_BR_IGRACA NUMBER NOT NULL,
	MIN_BR_IGRACA NUMBER NOT NULL,
	BONUS NUMBER NOT NULL,
	PLASMAN NUMBER NOT NULL,
	CONSTRAINT TIM_PK PRIMARY KEY (ID)
);

CREATE TABLE IGRAC
(
	ID NUMBER,
	ID_TIMA NUMBER,
	NADIMAK VARCHAR(50) UNIQUE NOT NULL,
	LOZINKA VARCHAR(50) NOT NULL,
	IME VARCHAR(50) NOT NULL,
	PREZIME VARCHAR(50) NOT NULL,
	POL CHAR(1) CHECK(POL IN('M','Z')) NOT NULL,
	UZRAST NUMBER NOT NULL,
	CONSTRAINT IGRAC_PK PRIMARY KEY (ID),
	CONSTRAINT IGRAC_TIM_FK FOREIGN KEY (ID_TIMA) REFERENCES TIM(ID)
);

CREATE TABLE SESIJA
(
	ID NUMBER,
	ID_IGRACA NUMBER NOT NULL,
	VREME_POCETKA TIMESTAMP NOT NULL,
	VREME_ZAVRSETKA TIMESTAMP NOT NULL,
	BROJ_BODOVA NUMBER NOT NULL,
	KOLICINA_ZLATA NUMBER NOT NULL,
	CONSTRAINT SESIJA_PK PRIMARY KEY (ID),
	CONSTRAINT SESIJA_IGRAC_FK FOREIGN KEY (ID_IGRACA) REFERENCES IGRAC(ID)
);

CREATE TABLE STAZA
(
	ID NUMBER,
	NAZIV VARCHAR(70) UNIQUE NOT NULL,
	TIMSKA CHAR(1) CHECK(TIMSKA IN('T','F')) NOT NULL,
	BONUS NUMBER NOT NULL,
	CONSTRAINT STAZA_PK PRIMARY KEY (ID)
);

CREATE TABLE PRELAZAK
(
	ID NUMBER,
	ID_IGRACA NUMBER,
	ID_TIMA NUMBER,
	ID_STAZE NUMBER NOT NULL,
	USPESAN CHAR(1) CHECK(USPESAN IN('T','F')) NOT NULL,
	BROJ_SAVLADANIH_NEPRIJATELJA NUMBER NOT NULL,
	CONSTRAINT PRELAZAK_PK PRIMARY KEY (ID),
	CONSTRAINT PRELAZAK_IGRAC_FK FOREIGN KEY (ID_IGRACA) REFERENCES IGRAC(ID),
	CONSTRAINT PRELAZAK_TIM_FK FOREIGN KEY (ID_TIMA) REFERENCES TIM(ID),
	CONSTRAINT PRELAZAK_STAZA_FK FOREIGN KEY (ID_STAZE) REFERENCES STAZA(ID)
);

CREATE TABLE PREDMET
(
	ID NUMBER,
	NAZIV VARCHAR(70) UNIQUE NOT NULL,
	BONUS_POENI NUMBER NOT NULL,
	OPIS VARCHAR(200) NOT NULL,
	CENA NUMBER NOT NULL,
	POTREBNO_ISKUSTVA NUMBER NOT NULL,
	F_ORUZJE CHAR(1) CHECK(F_ORUZJE IN('T','F')) NOT NULL,
	TIP_ORUZJA VARCHAR(30),
	POENI_NAPADA NUMBER,
	F_OKLOP CHAR(1) CHECK(F_OKLOP IN('T','F')) NOT NULL,
	POENI_ODBRANE NUMBER,
	CONSTRAINT PREDMET_PK PRIMARY KEY (ID)
);

CREATE TABLE LIK
(
	ID NUMBER,
	ID_IGRACA NUMBER UNIQUE NOT NULL,
	STEPEN_ZAMORA NUMBER NOT NULL,
	NIVO_ZDRAVLJA NUMBER NOT NULL,
	ISKUSTVO NUMBER NOT NULL,
	KOLICINA_ZLATA NUMBER NOT NULL,
	RASA VARCHAR(50) CHECK(RASA IN ('VILENJAK','DEMON','PATULJAK','ORK','COVEK')) NOT NULL,
	NIVO_ENERGIJE NUMBER,
	TIP_ORUZJA VARCHAR(30),
	UMECE_SKRIVANJA NUMBER,
	F_POMOCNIK CHAR(1) CHECK(F_POMOCNIK IN('T','F')) NOT NULL,
	IME VARCHAR(50),
	BONUS NUMBER,
	CONSTRAINT LIK_PK PRIMARY KEY (ID),
	CONSTRAINT LIK_IGRAC_FK FOREIGN KEY (ID_IGRACA) REFERENCES IGRAC(ID)
);

CREATE TABLE LOPOV
(
	ID_LIKA NUMBER,
	NIVO_BUKE NUMBER NOT NULL,
	UKLANJANJE_ZAMKI CHAR(1) CHECK(UKLANJANJE_ZAMKI IN('T','F')) NOT NULL,
	CONSTRAINT LOPOV_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT LOPOV_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);

CREATE TABLE CAROBNJAK
(
	ID_LIKA NUMBER,
	CONSTRAINT CAROBNJAK_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT CAROBNJAK_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);

CREATE TABLE BORAC
(
	ID_LIKA NUMBER,
	STIT CHAR(1) CHECK(STIT IN('T','F')) NOT NULL,
	DVORUCNO_ORUZJE CHAR(1) CHECK(DVORUCNO_ORUZJE IN('T','F')) NOT NULL,
	CONSTRAINT BORAC_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT BORAC_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);

CREATE TABLE SVESTENIK
(
	ID_LIKA NUMBER,
	RELIGIJA VARCHAR(50) NOT NULL,
	LECI CHAR(1) CHECK(LECI IN('T','F')) NOT NULL,
	CONSTRAINT SVESTENIK_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT SVESTENIK_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);

CREATE TABLE OKLOPNIK
(
	ID_LIKA NUMBER,
	MAKS_TEZINA_OKLOPA NUMBER NOT NULL,
	CONSTRAINT OKLOPNIK_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT OKLOPNIK_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);

CREATE TABLE STRELAC
(
	ID_LIKA NUMBER,
	LUK_SAMOSTREL VARCHAR(50) CHECK(LUK_SAMOSTREL IN('LUK','SAMOSTREL')) NOT NULL,
	CONSTRAINT STRELAC_PK PRIMARY KEY (ID_LIKA),
	CONSTRAINT STRELAC_LIK_FK FOREIGN KEY (ID_LIKA) REFERENCES LIK(ID)
	ON DELETE CASCADE
);


CREATE TABLE POSEDUJE
(
	ID NUMBER,
	ID_IGRACA NUMBER NOT NULL,
	ID_PREDMETA NUMBER NOT NULL,
	CONSTRAINT POSEDUJE_PK PRIMARY KEY (ID),
	CONSTRAINT POSEDUJE_PREDMET_FK FOREIGN KEY (ID_PREDMETA) REFERENCES PREDMET(ID),
	CONSTRAINT POSEDUJE_IGRAC_FK FOREIGN KEY (ID_IGRACA) REFERENCES IGRAC(ID)
);

CREATE TABLE BORI_SE
(
	ID NUMBER,
	ID_TIM1 NUMBER NOT NULL,
	ID_TIM2 NUMBER NOT NULL,
	VREME_ODRZAVANJA TIMESTAMP NOT NULL,
	BONUS NUMBER NOT NULL,
	POBEDNIK NUMBER CHECK(POBEDNIK IN (1,2)) NOT NULL,
	CONSTRAINT BORI_SE_PK PRIMARY KEY (ID),
	CONSTRAINT BORI_TIM1_FK FOREIGN KEY (ID_TIM1) REFERENCES TIM(ID),
	CONSTRAINT BORI_TIM2_FK FOREIGN KEY (ID_TIM2) REFERENCES TIM(ID)
);

CREATE TABLE MAGIJA
(
	ID NUMBER,
	NAZIV VARCHAR(100) NOT NULL,
	CONSTRAINT MAGIJA_PK PRIMARY KEY (ID)	
);

CREATE TABLE BACA_MAGIJU
(
	ID NUMBER,
	ID_MAGIJE NUMBER NOT NULL,
	ID_CAROBNJAKA NUMBER NOT NULL,
	CONSTRAINT BACA_MAGIJU_PK PRIMARY KEY (ID),
	CONSTRAINT CAROBNJAK_FK FOREIGN KEY (ID_CAROBNJAKA) REFERENCES CAROBNJAK(ID_LIKA) ON DELETE CASCADE,
	CONSTRAINT MAGIJA_FK FOREIGN KEY (ID_MAGIJE) REFERENCES MAGIJA(ID)
);

CREATE TABLE BLAGOSLOV
(
	ID NUMBER,
	NAZIV VARCHAR(100) NOT NULL,
	CONSTRAINT BLAGOSLOV_PK PRIMARY KEY (ID)
);

CREATE TABLE KORISTI_BLAGOSLOV
(
	ID NUMBER,
	ID_BLAGOSLOVA NUMBER NOT NULL,
	ID_SVESTENIKA NUMBER NOT NULL,
	CONSTRAINT KORISTI_BLAGOSLOV_PK PRIMARY KEY (ID),
	CONSTRAINT SVESTENIK_FK FOREIGN KEY (ID_SVESTENIKA) REFERENCES SVESTENIK(ID_LIKA) ON DELETE CASCADE,
	CONSTRAINT BLAGOSLOV_FK FOREIGN KEY (ID_BLAGOSLOVA) REFERENCES BLAGOSLOV(ID)
);

CREATE TABLE DOZVOLJENA_RASA
(
	ID NUMBER,
	ID_PREDMETA NUMBER NOT NULL,
	DOZVOLJENA_RASA VARCHAR(50) NOT NULL,
	CONSTRAINT DOZVOLJENA_RASA_PK PRIMARY KEY (ID),
	CONSTRAINT RASA_PREDMET_FK FOREIGN KEY (ID_PREDMETA) REFERENCES PREDMET(ID)
);

CREATE TABLE DOZVOLJENA_KLASA
(
	ID NUMBER,
	ID_PREDMETA NUMBER NOT NULL,
	DOZVOLJENA_KLASA VARCHAR(50) NOT NULL,
	CONSTRAINT DOZVOLJENA_KLASA_PK PRIMARY KEY (ID),
	CONSTRAINT KLASA_PREDMET_FK FOREIGN KEY (ID_PREDMETA) REFERENCES PREDMET(ID)
);

CREATE TABLE NEOPHODNA_RASA
(
	ID NUMBER,
	ID_STAZE NUMBER NOT NULL,
	NEOPHODNA_RASA VARCHAR(50) NOT NULL,
	CONSTRAINT NEOPHODNA_RASA_PK PRIMARY KEY (ID),
	CONSTRAINT RASA_STAZA_FK FOREIGN KEY (ID_STAZE) REFERENCES STAZA(ID)
);

CREATE TABLE NEOPHODNA_KLASA
(
	ID NUMBER,
	ID_STAZE NUMBER NOT NULL,
	NEOPHODNA_KLASA VARCHAR(50) NOT NULL,
	CONSTRAINT NEOPHODNA_KLASA_PK PRIMARY KEY (ID),
	CONSTRAINT KLASA_STAZA_FK FOREIGN KEY (ID_STAZE) REFERENCES STAZA(ID)
);

CREATE SEQUENCE TIM_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER TIM_AUTO_ID
    BEFORE INSERT
    ON TIM
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT TIM_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE IGRAC_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER IGRAC_AUTO_ID
    BEFORE INSERT
    ON IGRAC
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT IGRAC_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE SESIJA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER SESIJA_AUTO_ID
    BEFORE INSERT
    ON SESIJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT SESIJA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE STAZA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER STAZA_AUTO_ID
    BEFORE INSERT
    ON STAZA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT STAZA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE PRELAZAK_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER PRELAZAK_AUTO_ID
    BEFORE INSERT
    ON PRELAZAK
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PRELAZAK_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE PREDMET_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER PREDMET_AUTO_ID
    BEFORE INSERT
    ON PREDMET
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT PREDMET_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE LIK_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER LIK_AUTO_ID
    BEFORE INSERT
    ON LIK
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT LIK_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE POSEDUJE_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER POSEDUJE_AUTO_ID
    BEFORE INSERT
    ON POSEDUJE
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT POSEDUJE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE BORI_SE_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER BORI_SE_AUTO_ID
    BEFORE INSERT
    ON BORI_SE
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT BORI_SE_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE MAGIJA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER MAGIJA_AUTO_ID
    BEFORE INSERT
    ON MAGIJA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT MAGIJA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE BLAGOSLOV_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER BLAGOSLOV_AUTO_ID
    BEFORE INSERT
    ON BLAGOSLOV
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT BLAGOSLOV_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE DOZVOLJENA_RASA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER DOZVOLJENA_RASA_AUTO_ID
    BEFORE INSERT
    ON DOZVOLJENA_RASA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT DOZVOLJENA_RASA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE DOZVOLJENA_KLASA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER DOZVOLJENA_KLASA_AUTO_ID
    BEFORE INSERT
    ON DOZVOLJENA_KLASA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT DOZVOLJENA_KLASA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE NEOPHODNA_RASA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER NEOPHODNA_RASA_AUTO_ID
    BEFORE INSERT
    ON NEOPHODNA_RASA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT NEOPHODNA_RASA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE NEOPHODNA_KLASA_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER NEOPHODNA_KLASA_AUTO_ID
    BEFORE INSERT
    ON NEOPHODNA_KLASA
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT NEOPHODNA_KLASA_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE BACA_MAGIJU_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER BACA_MAGIJU_AUTO_ID
    BEFORE INSERT
    ON BACA_MAGIJU
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT BACA_MAGIJU_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

/

CREATE SEQUENCE KORISTI_BLAGOSLOV_ID_SEQ MINVALUE 0 INCREMENT BY 1 START WITH 0 CACHE 20 ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER KORISTI_BLAGOSLOV_AUTO_ID
    BEFORE INSERT
    ON KORISTI_BLAGOSLOV
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT KORISTI_BLAGOSLOV_ID_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
